// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTeeq_LvhYSESuJvjPRsslVUE4l-lOKjk',
    appId: '1:427023478978:web:e10c6fc0e8a27b57660b5b',
    messagingSenderId: '427023478978',
    projectId: 'resqnet-f955d',
    authDomain: 'resqnet-f955d.firebaseapp.com',
    storageBucket: 'resqnet-f955d.firebasestorage.app',
    measurementId: 'G-LJBDX1X5MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDChld7yGNSC9GeT0uTFLgdGu2VzMUVoo',
    appId: '1:427023478978:android:8f14d966949e3cd4660b5b',
    messagingSenderId: '427023478978',
    projectId: 'resqnet-f955d',
    storageBucket: 'resqnet-f955d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATmXuTvz18eSTFtkEpOc7PqziozR6VrRo',
    appId: '1:427023478978:ios:26faee567d6fb68b660b5b',
    messagingSenderId: '427023478978',
    projectId: 'resqnet-f955d',
    storageBucket: 'resqnet-f955d.firebasestorage.app',
    androidClientId: '427023478978-0e4lp0vghvab47j6btsned2k7m64jdnl.apps.googleusercontent.com',
    iosClientId: '427023478978-1n593h8fuhrucrmn8arbab30h3o2gasb.apps.googleusercontent.com',
    iosBundleId: 'com.example.resqnet',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATmXuTvz18eSTFtkEpOc7PqziozR6VrRo',
    appId: '1:427023478978:ios:26faee567d6fb68b660b5b',
    messagingSenderId: '427023478978',
    projectId: 'resqnet-f955d',
    storageBucket: 'resqnet-f955d.firebasestorage.app',
    androidClientId: '427023478978-0e4lp0vghvab47j6btsned2k7m64jdnl.apps.googleusercontent.com',
    iosClientId: '427023478978-1n593h8fuhrucrmn8arbab30h3o2gasb.apps.googleusercontent.com',
    iosBundleId: 'com.example.resqnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTeeq_LvhYSESuJvjPRsslVUE4l-lOKjk',
    appId: '1:427023478978:web:a2770ad3edd218a8660b5b',
    messagingSenderId: '427023478978',
    projectId: 'resqnet-f955d',
    authDomain: 'resqnet-f955d.firebaseapp.com',
    storageBucket: 'resqnet-f955d.firebasestorage.app',
    measurementId: 'G-TDC0GSNDRX',
  );
}
