// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWJRtMqBncpF92kLOIIl6ZcF3ocVMnBN0',
    appId: '1:349015883051:web:49a28da65a5539e01f596e',
    messagingSenderId: '349015883051',
    projectId: 'resqnet-2024',
    authDomain: 'resqnet-2024.firebaseapp.com',
    storageBucket: 'resqnet-2024.firebasestorage.app',
    measurementId: 'G-KFTR3QJB56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKe4JRJkY6jPP6DNsuuMw31hkkwq2Qp_g',
    appId: '1:349015883051:android:596e641dbd9d2bbc1f596e',
    messagingSenderId: '349015883051',
    projectId: 'resqnet-2024',
    storageBucket: 'resqnet-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcw_R5yJCPW-mijFyB9vnKoED5I48nnBM',
    appId: '1:349015883051:ios:14aefbefce1e2fd81f596e',
    messagingSenderId: '349015883051',
    projectId: 'resqnet-2024',
    storageBucket: 'resqnet-2024.firebasestorage.app',
    iosBundleId: 'com.example.resqnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcw_R5yJCPW-mijFyB9vnKoED5I48nnBM',
    appId: '1:349015883051:ios:14aefbefce1e2fd81f596e',
    messagingSenderId: '349015883051',
    projectId: 'resqnet-2024',
    storageBucket: 'resqnet-2024.firebasestorage.app',
    iosBundleId: 'com.example.resqnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWJRtMqBncpF92kLOIIl6ZcF3ocVMnBN0',
    appId: '1:349015883051:web:d4303e928c22d8be1f596e',
    messagingSenderId: '349015883051',
    projectId: 'resqnet-2024',
    authDomain: 'resqnet-2024.firebaseapp.com',
    storageBucket: 'resqnet-2024.firebasestorage.app',
    measurementId: 'G-J6Z6DTTVR2',
  );
}
