import 'package:flutter/material.dart';
import 'origin_envelope.dart';

enum EmergencyType {
  medical,
  fire,
  flood,
  earthquake,
  trapped,
  rescue,
  general,
}

enum PriorityLevel {
  critical,
  high,
  medium,
  low,
}

class EmergencyMessage {
  final String id;
  final String senderId;
  final String senderName;
  final String message;
  final EmergencyType type;
  final PriorityLevel priority;
  final double? latitude;
  final double? longitude;
  final DateTime timestamp;
  final int hopCount;
  final bool isRelayed;
  final String? bloodGroup;
  final String? allergies;
  final String? medications;
  final int? batteryLevel;
  // A recorded voice note, base64-encoded so it travels inside this same
  // message — over the mesh (offline) exactly like Firestore (online),
  // for people who can't type. Kept short (see VoiceNoteService) so it
  // stays small enough to relay over Bluetooth/Wi-Fi Direct.
  final String? audioBase64;
  final int? audioDurationSeconds;

  // --- Phase 5: signed mesh envelope fields (additive) ---
  //
  // `id` already serves as the signed event's `eventId` (unchanged from
  // before this phase — sos_service.dart's sosToBroadcastMessage has
  // always set it to the same id sent to the backend). The fields below
  // are new. Origin fields (originEnvelope's own contents) are immutable
  // once signed; `messageId`/`relayPath` are transport metadata a relay
  // is expected to change and are deliberately NOT part of what's signed
  // (see origin_envelope.dart's own doc comment on why).

  /// Identifies this specific transmission/relay hop — distinct from
  /// `id` (the emergency event itself), which stays constant across every
  /// hop. Regenerated by each relay when it forwards (see MeshService),
  /// so mesh-level duplicate/loop detection can key on
  /// (id, senderId-at-that-hop) pairs without confusing "the same event,
  /// relayed again" with "the same transmission, received twice".
  final String? messageId;

  /// The signed cryptographic origin claim (Phase 1/4) — null when this
  /// device could not sign at creation time (e.g. no native key module
  /// available yet), in which case this message carries no stronger
  /// authentication than "arrived over mesh transport". Never fabricated
  /// or backfilled with a fake signature.
  final OriginEnvelope? originEnvelope;

  /// Hop budget (Phase 5/7) — checked by every relay against the CURRENT
  /// `hopCount` before forwarding. Matches `originEnvelope`'s own signed
  /// `maxHops` when an envelope is present (so a relay can't raise the
  /// limit by lying about this field independently of the signed value);
  /// falls back to [defaultMaxHops] for envelope-less messages.
  final int maxHops;

  /// Bounded list of relay device ids this message has passed through —
  /// transport metadata only, never signed, never trusted as proof of
  /// path integrity. Used for basic loop avoidance (a relay that sees its
  /// own id already in this list drops the message rather than
  /// re-forwarding it) and diagnostics, not as a security control.
  final List<String> relayPath;

  /// When this event stops being eligible for relay/backend acceptance
  /// (Phase 5/9's TTL). Matches `originEnvelope.expiresAt` when present.
  final DateTime? expiresAt;

  /// Set locally (never serialized, never trusted if it somehow arrived
  /// from elsewhere) by MeshService right after this device itself runs
  /// `verifyOriginEnvelopeLocally` against `originEnvelope` on receipt.
  /// True only for `signatureValidSelfConsistent` — see that function's
  /// doc comment for exactly what this does and does not prove. Always
  /// false for a message this device itself created/broadcast (this
  /// device doesn't need to verify its own signature).
  final bool originVerifiedLocally;

  static const int defaultMaxHops = 8;

  EmergencyMessage({
    required this.id,
    required this.senderId,
    required this.senderName,
    required this.message,
    required this.type,
    required this.priority,
    this.latitude,
    this.longitude,
    required this.timestamp,
    this.hopCount = 0,
    this.isRelayed = false,
    this.bloodGroup,
    this.allergies,
    this.medications,
    this.batteryLevel,
    this.audioBase64,
    this.audioDurationSeconds,
    this.messageId,
    this.originEnvelope,
    this.maxHops = defaultMaxHops,
    this.relayPath = const [],
    this.expiresAt,
    this.originVerifiedLocally = false,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'senderId': senderId,
        'senderName': senderName,
        'message': message,
        'type': type.name,
        'priority': priority.name,
        'latitude': latitude,
        'longitude': longitude,
        'timestamp': timestamp.millisecondsSinceEpoch,
        'hopCount': hopCount,
        'isRelayed': isRelayed,
        'bloodGroup': bloodGroup,
        'allergies': allergies,
        'medications': medications,
        'batteryLevel': batteryLevel,
        'audioBase64': audioBase64,
        'audioDurationSeconds': audioDurationSeconds,
        'messageId': messageId,
        'originEnvelope': originEnvelope?.toJson(),
        'maxHops': maxHops,
        'relayPath': relayPath,
        'expiresAt': expiresAt?.toIso8601String(),
      };

  factory EmergencyMessage.fromJson(Map<String, dynamic> json) =>
      EmergencyMessage(
        id: json['id'],
        senderId: json['senderId'],
        senderName: json['senderName'],
        message: json['message'],
        type: EmergencyType.values.firstWhere(
            (e) => e.name == json['type'],
            orElse: () => EmergencyType.general),
        priority: PriorityLevel.values.firstWhere(
            (e) => e.name == json['priority'],
            orElse: () => PriorityLevel.low),
        latitude: json['latitude']?.toDouble(),
        longitude: json['longitude']?.toDouble(),
        timestamp:
            DateTime.fromMillisecondsSinceEpoch(json['timestamp'] as int),
        hopCount: json['hopCount'] ?? 0,
        isRelayed: json['isRelayed'] ?? false,
        bloodGroup: json['bloodGroup'],
        allergies: json['allergies'],
        medications: json['medications'],
        batteryLevel: json['batteryLevel'],
        audioBase64: json['audioBase64'],
        audioDurationSeconds: json['audioDurationSeconds'],
        messageId: json['messageId'] as String?,
        originEnvelope: json['originEnvelope'] != null
            ? OriginEnvelope.fromJson(json['originEnvelope'] as Map<String, dynamic>)
            : null,
        maxHops: json['maxHops'] as int? ?? defaultMaxHops,
        relayPath: (json['relayPath'] as List?)?.cast<String>() ?? const [],
        expiresAt: json['expiresAt'] != null ? DateTime.parse(json['expiresAt'] as String) : null,
      );

  EmergencyMessage copyWith({
    String? id,
    String? senderId,
    String? senderName,
    String? message,
    EmergencyType? type,
    PriorityLevel? priority,
    double? latitude,
    double? longitude,
    DateTime? timestamp,
    int? hopCount,
    bool? isRelayed,
    String? bloodGroup,
    String? allergies,
    String? medications,
    int? batteryLevel,
    String? audioBase64,
    int? audioDurationSeconds,
    String? messageId,
    OriginEnvelope? originEnvelope,
    int? maxHops,
    List<String>? relayPath,
    DateTime? expiresAt,
    bool? originVerifiedLocally,
  }) =>
      EmergencyMessage(
        id: id ?? this.id,
        senderId: senderId ?? this.senderId,
        senderName: senderName ?? this.senderName,
        message: message ?? this.message,
        type: type ?? this.type,
        priority: priority ?? this.priority,
        latitude: latitude ?? this.latitude,
        longitude: longitude ?? this.longitude,
        timestamp: timestamp ?? this.timestamp,
        hopCount: hopCount ?? this.hopCount,
        isRelayed: isRelayed ?? this.isRelayed,
        bloodGroup: bloodGroup ?? this.bloodGroup,
        allergies: allergies ?? this.allergies,
        medications: medications ?? this.medications,
        batteryLevel: batteryLevel ?? this.batteryLevel,
        audioBase64: audioBase64 ?? this.audioBase64,
        audioDurationSeconds: audioDurationSeconds ?? this.audioDurationSeconds,
        messageId: messageId ?? this.messageId,
        originEnvelope: originEnvelope ?? this.originEnvelope,
        maxHops: maxHops ?? this.maxHops,
        relayPath: relayPath ?? this.relayPath,
        expiresAt: expiresAt ?? this.expiresAt,
        originVerifiedLocally: originVerifiedLocally ?? this.originVerifiedLocally,
      );

  /// True once `hopCount` has reached this message's hop budget — a
  /// relay must not forward it any further (Phase 5/7's hop-limit
  /// enforcement).
  bool get hasReachedMaxHops => hopCount >= maxHops;

  /// True once past `expiresAt` — an expired event must not continue
  /// propagating (Phase 5/7's TTL enforcement). Messages with no
  /// `expiresAt` (legacy/envelope-less) never expire by this check alone.
  bool get isExpired => expiresAt != null && DateTime.now().isAfter(expiresAt!);

  Color get priorityColor {
    switch (priority) {
      case PriorityLevel.critical:
        return const Color(0xFFD32F2F);
      case PriorityLevel.high:
        return const Color(0xFFFF6F00);
      case PriorityLevel.medium:
        return const Color(0xFFF9A825);
      case PriorityLevel.low:
        return const Color(0xFF2E7D32);
    }
  }

  IconData get typeIcon {
    switch (type) {
      case EmergencyType.medical:
        return Icons.local_hospital;
      case EmergencyType.fire:
        return Icons.local_fire_department;
      case EmergencyType.flood:
        return Icons.water;
      case EmergencyType.earthquake:
        return Icons.terrain;
      case EmergencyType.trapped:
        return Icons.person_pin_circle;
      case EmergencyType.rescue:
        return Icons.emergency;
      case EmergencyType.general:
        return Icons.warning;
    }
  }
}